### ISSUE TITLE
Header、Footerを作成する。

### ISSUE THREAD

**Issue by kazu-2020** [kazu-2020/arrangy#13]
## 要件
ヘッダーとフッダーを作成する。

## タスク
- [x] ヘッダーには「Arrangy」を表記する  #14
- [x] ログイン前は、ヘッダーに「新規登録/ログインページ」へのリンクを作成する。 #14
- [x] ログイン後、ヘッダーに「ログアウト」用のリンクを作成する  #14
- [x] フッターには、「利用規約」、「お問い合わせ」ページへのリンクを作成する。  #14
